### ISSUE TITLE
Quest - [Primal Strike: 2696]

### ISSUE THREAD

**Issue by Hazor-Hellscream** [Hazor-Hellscream/Project-Hellscream-Info#1]
Quest - [Primal Strike: 2696] 
![image](https://user-images.githubusercontent.com/53961554/74089664-557b3b00-4aef-11ea-9386-80f74029edef.png)

Training dummies are not calculating the spell trigger used.

Priority:
Medium

WoW Head Link:
(https://www.wowhead.com/quest=26969/primal-strike)

**Comment by ffdevill** [comment]
fixed added sql to pull request once done will be fixed
