### ISSUE TITLE
Spell - [Storm bolt: 107570]

### ISSUE THREAD

**Issue by SimeonGavrilov** [Hazor-Hellscream/Project-Hellscream-Info#1017]
The hammer model is not true.
Stun appears a second after the hammer hits the target.

Priority: Hight

Wowhead:
(https://www.wowhead.com/spell=107570/storm-bolt)

**Comment by Nyr97** [comment]
Fixed: now the stun effect applies on dealing the dmg, rather than 1s later. It will be avaliable on next update.
