### ISSUE TITLE
Quest - [Onward, to Light's Hope Chapel: 27373]

### ISSUE THREAD

**Issue by Holyblaster** [Hazor-Hellscream/Project-Hellscream-Info#102]
Information: caravan is absent
![WoWScrnShot_020920_154309](https://user-images.githubusercontent.com/60840202/74126233-da9a4900-4bf0-11ea-994b-7c61714a6c0c.jpg)

**Comment by Holyblaster** [comment]
work

**Comment by SimeonGavrilov** [comment]
![WoWScrnShot_033120_105737](https://user-images.githubusercontent.com/52416849/77996354-808b4980-733e-11ea-85ed-a95cd23126d4.jpg)

It is don't working for now,
there is no any interaction.
