### ISSUE TITLE
Glyph - [Raging Wind]

### ISSUE THREAD

**Issue by SimeonGavrilov** [Hazor-Hellscream/Project-Hellscream-Info#1021]
Glyph proc from any spells. Must proc only from "Raging Blow"

Priority: Low

Link:
(https://wowwiki.fandom.com/wiki/Glyph_of_Raging_Wind)
Raging Blow:
(https://www.wowhead.com/spell=85288/raging-blow)

**Comment by Nyr97** [comment]
Now it only procs off from Raging Blow. It will added on next update.
