### ISSUE TITLE
Mistweaver Monk - [Mana Tea]

### ISSUE THREAD

**Issue by Dabimann** [Hazor-Hellscream/Project-Hellscream-Info#1034]
![Screenshot_3](https://user-images.githubusercontent.com/64604210/81213737-1e75d200-8fd7-11ea-87a6-25bb697fe292.png)

I haven't fully tested it yet, but i am pretty sure only the Crit part is working.
After like 20 Chi spent, i am at a whopping 1 Stack, so i am pretty sure the Chi part is not working at all and the 1 Stack came from a Crit

**Comment by Nyr97** [comment]
It does work correctly, you just need to be in combat to build any Mana Tea.
