### ISSUE TITLE
Kazzak attack speed

### ISSUE THREAD

**Issue by yo931** [Hazor-Hellscream/Project-Hellscream-Info#1036]
His attack speed seems to be 0.5 sec but I believe it should be 1.8 sec according to a few videos I have watched and websites like this - https://vanillawowdb.com/?npc=12397

**Comment by SimeonGavrilov** [comment]
he just staying and didn't anything
![image](https://user-images.githubusercontent.com/52416849/81223800-a9ff5b00-8ff7-11ea-8546-940b03f3c1f4.png)

**Comment by SimeonGavrilov** [comment]
1) (https://www.wowhead.com/spell=32963/shadow-bolt-volley) - he cast it cast 3-4 time in a row (in one sec). He do it all time. Must cast this spell just under (https://www.wowhead.com/spell=32964/frenzy)
2) Boss not auto-attack. He just stay and cast spell from first point, but if anyone stay in melee, boss start auto-attack and cast shadow-bolts in same time.

**Comment by SimeonGavrilov** [comment]
3. (https://www.wowhead.com/spell=36706/thunderclap) too many dmg, on classic must be only 200 dmg
![image](https://user-images.githubusercontent.com/52416849/81401587-b3480f00-9140-11ea-8f92-77d4ca00968e.png)
this is our server:
![image](https://user-images.githubusercontent.com/52416849/81401704-ef7b6f80-9140-11ea-8fcf-860edeaed9f2.png)

**Comment by SimeonGavrilov** [comment]
4. After pull, he still go on his marshrut about 4-10 sec and cast shadow bolt.
He must go to his target after pull.

**Comment by SimeonGavrilov** [comment]
5. Boss has incorrect loot.

**Comment by EyalMK** [comment]
Boss was not scripted when you killed him. Not supposed to be released yet. Kazzak has been scripted and tested on PTR and will be fixed in live tomorrow when it is released.
Boss loot is correct - items have low chance is all as per wowhead.

Won't fix.
