### ISSUE TITLE
Quest - [Un-Chartered: 24955]

### ISSUE THREAD

**Issue by szentigrad3** [Hazor-Hellscream/Project-Hellscream-Info#1050]
no gossip option for orges to sign the carter, the Dunemaul  ogre mage go friendly but the Dunemaul enforcers do not > https://www.wowhead.com/quest=24955/un-chartered

**Comment by EyalMK** [comment]
Fixed and tested, now completely blizzlike with Megs and Dunemaul Emissary text at completion as well. Closed.
