### ISSUE TITLE
NPC: Kodos in Northern Barrens are unattackable

### ISSUE THREAD

**Issue by Sundorian** [Hazor-Hellscream/Project-Hellscream-Info#1056]
Several Kodos in the Nothern Barrens are unattackable.  I have not hunted down and tested whether they all are or not.

**Comment by EyalMK** [comment]
What are they IDs?

**Comment by Sundorian** [comment]
I cant click on them at all so I dont know.

**Comment by EyalMK** [comment]
Fixed and tested.
