### ISSUE TITLE
NPC: Ulthaan appears dead but moves

### ISSUE THREAD

**Issue by Sundorian** [Hazor-Hellscream/Project-Hellscream-Info#1058]
NPC - Ulthaan id3960 (wowhead BfA)

in the comments in wowhead is this -

By Sabrotin (13,703 –  1·21·21)  on 2011/01/07 (Patch 4.0.3) |
I can officialy confirm from in-game... Ulthaan has indeed been removed from the game. His corpse can be found (as the above map now shows) at 2 different spawn points: 48.6, 64.1 or 50.0, 66.7. Since the move of Big Bear Steak recipe to Super-Seller 680 in Desolace, and Lean Venison to Vendor-Tron 1000 also in Desolace, this NPC no longer has any special feature. Thus, one missing NPC problem solved. :)

![image](https://user-images.githubusercontent.com/45952468/81775216-06f48880-94b2-11ea-80d1-8e40be7f0018.png)

![WoWScrnShot_051320_003200](https://user-images.githubusercontent.com/45952468/81775653-da8d3c00-94b2-11ea-91c1-3aaded00db5c.png)

**Comment by EyalMK** [comment]
I don't get it? The NPC is where he's supposed to be except for his tame status appearing which I'll fix right away.

**Comment by EyalMK** [comment]
Didn't read title. Fixed and closed.
