### ISSUE TITLE
World Dragons

### ISSUE THREAD

**Issue by yo931** [Hazor-Hellscream/Project-Hellscream-Info#1059]
She is resetting when you pull her off the platform, should be able to pull her around the entire area

Tail sweep (15847) is hitting from her sides instead of the tail, you can stand directly on the tail and not get damaged

You can pull her from the top of the pillars and she will not evade but also won't melee attack you

Aura of Nature not working - https://classic.wowhead.com/spell=25044/aura-of-nature 
If a player with Mark of Nature comes within 100 yards of the boss, this aura will cause the player to enter into an undispellable sleep for 2 minutes.

**Comment by yo931** [comment]
Update, was able to solo Taerare since he doesn't evade and can be attacked without getting hit

Also the tail sweep seems to be happening every 2 seconds with his melee attack. Should be slow enough to walk through him or turn the boss while killing him properly, so longer than 5 seconds in between tail swipes would be more blizzlike.

Also I believe it should drop gold when killing, probably like 50g-100g or so.

**Comment by EyalMK** [comment]
2 sec tail swipe is the blizzlike timer, as for the other issues Hazor is on it

**Comment by EyalMK** [comment]
Not relevant anymore. Closed.
