### ISSUE TITLE
Quest - [Take it to the Tree: 28357]

### ISSUE THREAD

**Issue by 601bukaj** [Hazor-Hellscream/Project-Hellscream-Info#119]
Information:
Not all Talonbranch Defenders are counting for quest progress.

Priority:
Low

WoWhead link:
https://www.wowhead.com/quest=28357/take-it-to-the-tree

**Comment by 601bukaj** [comment]
Not fixed

**Comment by szentigrad3** [comment]
Not all Talonbranch Defenders are counting for quest progress < confirmed, irontree choppers are attacking them, not working as of 0.1.6a
