### ISSUE TITLE
Quest - [Slap and Cap: 28336]

### ISSUE THREAD

**Issue by 601bukaj** [Hazor-Hellscream/Project-Hellscream-Info#120]
Information:
Can't interact with Panicked Workers.

Priority:
Medium

WoWhead link:
https://www.wowhead.com/quest=28336/slap-and-cap

**Comment by 601bukaj** [comment]
Can interact but cannot slap them.

**Comment by szentigrad3** [comment]
Can interact but cannot slap them opens a dialog box, not fixed as of 0.1.6a
