### ISSUE TITLE
Quest - [The Coastal Menace: 26349]

### ISSUE THREAD

**Issue by ShaldarWoW** [Hazor-Hellscream/Project-Hellscream-Info#134]
Quest - [The Coastal Menace: 26349]

The NPC Old Murk-Eye isn't spawning.

Related WoW Head links:
Quest: (https://www.wowhead.com/quest=26349/the-coastal-menace)
Old Murk-Eye: (https://www.wowhead.com/npc=391/old-murk-eye)

**Comment by szentigrad3** [comment]
quest works as of 0.1.6a
