### ISSUE TITLE
Quest - [Ever So Lonely: 24974] 

### ISSUE THREAD

**Issue by AI38** [Hazor-Hellscream/Project-Hellscream-Info#135]
![WoWScrnShot_021120_173224](https://user-images.githubusercontent.com/60925596/74260657-369cc480-4cfa-11ea-97e5-50265f002604.jpg)

Murloc can't be leashed, unable to advance futher in the quest 

Priority: Low

WoWHead link:
(https://www.wowhead.com/quest=24974/ever-so-lonely)

**Comment by szentigrad3** [comment]
still doesn't work

**Comment by EyalMK** [comment]
Fixed and tested.
