### ISSUE TITLE
Quest: What's Haunting Witch Hill? 27188

### ISSUE THREAD

**Issue by Goretech** [Hazor-Hellscream/Project-Hellscream-Info#142]
Cant gather information from spirits.

https://www.wowhead.com/quest=27188/whats-haunting-witch-hill

**Comment by szentigrad3** [comment]
works but not blizzlike > when u kill a risen spirit when you kill it a npc spawns, but atm the npcs are spawned all over the map > https://puu.sh/FuNt1/f985c959de.jpg
