### ISSUE TITLE
Quest - [A Curse We Cannot Lift: 26720]

### ISSUE THREAD

**Issue by ShaldarWoW** [Hazor-Hellscream/Project-Hellscream-Info#17]
Quest - [A Curse We Cannot Lift: 26720]

![imagen](https://user-images.githubusercontent.com/60824117/74091696-7aa18680-4aba-11ea-8b4e-d64a42109c3b.png)

It's impossible to attack the worgen in order to lower its health and throw the provided Harris's Ampule at him.
Instead, the ampule is consumed on use after displaying the throwing animation and nothing happens.

Priority:
Medium

WoW Head link:
(https://www.wowhead.com/quest=26720/a-curse-we-cannot-lift)

**Comment by Goretech** [comment]
Working, can be closed.
