### ISSUE TITLE
Quest-[Can't Get Ear-nough...: 11867]

### ISSUE THREAD

**Issue by Goretech** [Hazor-Hellscream/Project-Hellscream-Info#179]
Mobs drop quest item, but 60% of time you cant loot it, says already looted.

https://www.wowhead.com/quest=11867/cant-get-ear-nough

**Comment by Rakarth802** [comment]
Got through the entire quest without this happening. Fixed.

**Comment by Firoqt** [comment]
@Hazor-Hellscream Can be closed.
