### ISSUE TITLE
Quest-[The Final Ritual: 26170]

### ISSUE THREAD

**Issue by Holyblaster** [Hazor-Hellscream/Project-Hellscream-Info#184]
Info: NPC Loramus is missing
https://www.wowhead.com/quest=26170/the-final-ritual
![WoWScrnShot_021420_101830](https://user-images.githubusercontent.com/60840202/74555505-47a53a00-4f75-11ea-8ad8-a06df013ff60.jpg)

**Comment by Holyblaster** [comment]
NPC Loramus still missing

**Comment by EyalMK** [comment]
Actually Loramus is spawned. This NPC is missing from the second location where this quest is supposed to be picked up, the NPC is supposed to be near Loramus inside the cave.

I scripted these two quests. To-do: spawn Kasim next to Loramus inside cave near Dreadmaul Post.

**Comment by EyalMK** [comment]
Quest chain is a work in progress and about 80% done. Added Loramus and phasing system is being implemented. WIP. player will now be put in a different phase than Loramus when he completes the quest https://wow.gamepedia.com/Time_is_Short_(Alliance), at which point in the questline Loramus is supposed to be 'dead' and player will be put in Loramus's phase when he finishes the objectives of https://wow.gamepedia.com/Not_Just_Any_Body_(Alliance)
