### ISSUE TITLE
Spell - [Conjure Refreshment: 42955]

### ISSUE THREAD

**Issue by 601bukaj** [Hazor-Hellscream/Project-Hellscream-Info#186]
Information:
Does not Conjures Refreshment.

WoWhead link:
https://www.wowhead.com/spell=42955/conjure-refreshment

**Comment by Firoqt** [comment]
Wrote new script. Test again and let us know here or in Discord.

**Comment by 601bukaj** [comment]
Still not working. If it helps I am currently at level 69.

**Comment by 601bukaj** [comment]
With the release of [Major Update 0.0.9], the issue has been resolved.
