### ISSUE TITLE
Quest - [Healing the Lake: 9294]

### ISSUE THREAD

**Issue by ShaldarWoW** [Hazor-Hellscream/Project-Hellscream-Info#189]
Quest - [Healing the Lake: 9294]

![imagen](https://user-images.githubusercontent.com/60824117/74604620-04a3ad80-50c0-11ea-8bb4-3bdfa46fe606.png)

Can't activate the Neutralizing Agent quest item near the crystal in the lake.

Related WoW Head links:
Quest: (https://www.wowhead.com/quest=9294/healing-the-lake)
Neutralizing Agent: (https://www.wowhead.com/item=22955/neutralizing-agent)

**Comment by Goretech** [comment]
Working now.
