### ISSUE TITLE
Quest - [I Think She's Hungry: 26739]

### ISSUE THREAD

**Issue by ShaldarWoW** [Hazor-Hellscream/Project-Hellscream-Info#19]
Quest - [I Think She's Hungry: 26739]

![imagen](https://user-images.githubusercontent.com/60824117/74092345-b4768b00-4ac2-11ea-97d4-7da20601c0f7.png)

The hatchling doesn't bite the corpse after summoning it with the provided quest item.

Priority:
Medium

WoW Head link:
(https://www.wowhead.com/quest=26739/i-think-shes-hungry)

**Comment by Goretech** [comment]
Working, can be closed.
