### ISSUE TITLE
Quest-Honor the Dead: 27180]

### ISSUE THREAD

**Issue by Holyblaster** [Hazor-Hellscream/Project-Hellscream-Info#217]
Info: can not looted
https://www.wowhead.com/quest=27180/honor-the-dead
![WoWScrnShot_021820_214313](https://user-images.githubusercontent.com/60840202/74838065-4f315e00-533c-11ea-9c09-8233712e9eff.jpg)

**Comment by szentigrad3** [comment]
working as of 0.1.6a
