### ISSUE TITLE
Quest:[A taste for grouper:13537]

### ISSUE THREAD

**Issue by Goretech** [Hazor-Hellscream/Project-Hellscream-Info#221]
Fishing is not working.

https://www.wowhead.com/quest=13537/a-taste-for-grouper

**Comment by Goretech** [comment]
Working, took me 27 tries to get first fish but working.

**Comment by Firoqt** [comment]
@Goretech Yeah, according to the comments in Wowhead, it's a low chance. Someone went from 1-45 trying to catch the first fish lol.

@Hazor-Hellscream Working as intended, can be closed.
