### ISSUE TITLE
Quest:[Ending the threat:13515]

### ISSUE THREAD

**Issue by Goretech** [Hazor-Hellscream/Project-Hellscream-Info#224]
No credit for killing the mob.

https://www.wowhead.com/quest=13515/ending-the-threat

**Comment by Goretech** [comment]
Working.

**Comment by Firoqt** [comment]
@Hazor-Hellscream Can be closed.

**Comment by EyalMK** [comment]
Reworked the quest and made it blizzlike.
The Spell Shattershield Arrow now works as intended and removes the Aegis of The Shatterspear aura from Jor'kil
