### ISSUE TITLE
Quest - [Young And Vicious:24626]

### ISSUE THREAD

**Issue by senbonsakura** [Hazor-Hellscream/Project-Hellscream-Info#246]
1- Swiftclaw should be running around the isle but he's just standing in a place.
2 - After using the lasso, it should be mountable. It just keeps attacking you. It stopped after a while somehow.
3 - Can't finish the quest when after bringing it to the raptor pen. Can't complete the quest.

![image](https://user-images.githubusercontent.com/7535384/75067366-e0036780-54fd-11ea-9526-a8d51e1ab8e0.png)

Priority: High
Wowhead link: https://www.wowhead.com/quest=24626/young-and-vicious

**Comment by EyalMK** [comment]
Fixed in the last patch.
