### ISSUE TITLE
Quest - [Kyle's Gone Missing!:11129]

### ISSUE THREAD

**Issue by cgsnascar** [Hazor-Hellscream/Project-Hellscream-Info#247]
1. There are about 5 "Kyle the Frenzied" walking around Bloodhoof Village
2. When you feed Kyle, it states "Kyle fed 1/1" but the quest does not complete.

![WoWScrnShot_022120_165923](https://user-images.githubusercontent.com/14172411/75075365-a4e84080-54cb-11ea-8ad7-fcc56a94c71c.jpg)
![WoWScrnShot_022120_165925](https://user-images.githubusercontent.com/14172411/75075374-a7e33100-54cb-11ea-9728-a5a809161817.jpg)

**Comment by EyalMK** [comment]
Fixed in the last patch.
