### ISSUE TITLE
Quest-Follow that Gyro-Copter!: 24491

### ISSUE THREAD

**Issue by Holyblaster** [Hazor-Hellscream/Project-Hellscream-Info#248]
Info: Missing NPC Milo Geartwinge
https://www.wowhead.com/quest=24491/follow-that-gyro-copter
![WoWScrnShot_022220_103744](https://user-images.githubusercontent.com/60840202/75089624-3ca16980-5574-11ea-9aed-cda7f8331f44.jpg)

**Comment by EyalMK** [comment]
Fixed in last patch.
