### ISSUE TITLE
Creature - [Ironmarch Scout: 76886]

### ISSUE THREAD

**Issue by Saesuri** [Hazor-Hellscream/Project-Hellscream-Info#258]
![image](https://user-images.githubusercontent.com/9422623/75098516-f9f08900-5595-11ea-81ff-e78f8895cbc3.png)
Ironmarch Scout should lose stealth when engaged in combat.

Priority:
Medium

Wowhead:
https://www.wowhead.com/npc=76886/ironmarch-scout

**Comment by EyalMK** [comment]
Fixed and tested.
