### ISSUE TITLE
Spell - [Stagger: 124255]

### ISSUE THREAD

**Issue by Saesuri** [Hazor-Hellscream/Project-Hellscream-Info#261]
![WoWScrnShot_022220_180649](https://user-images.githubusercontent.com/9422623/75099276-7c7d4680-559e-11ea-898d-105193d6ce2a.jpg)
You can be at 1 health with only stagger ticking and not die. Stagger should not kill the monk.

Priority:
Critical

Wowhead link:
https://www.wowhead.com/spell=124255/stagger

**Comment by Firoqt** [comment]
Fixed, applied next update.

**Comment by Saesuri** [comment]
Fixed.
