### ISSUE TITLE
Spell - [Paralysis: 115078]

### ISSUE THREAD

**Issue by Saesuri** [Hazor-Hellscream/Project-Hellscream-Info#263]
![image](https://user-images.githubusercontent.com/9422623/75099598-32965f80-55a2-11ea-9caa-ad0a2b378ad4.png)
Casting paralysis on mobs should not aggro them into combat.

Priority:
High

Wowhead link:
https://www.wowhead.com/spell=115078/paralysis

**Comment by Firoqt** [comment]
Tested - Works.
