### ISSUE TITLE
Quest : (Winds of Change)

### ISSUE THREAD

**Issue by N3wkid92** [Hazor-Hellscream/Project-Hellscream-Info#269]
Olin should be in the Cave, Questmap is wrong too. Mobs spawn to "defend him" but Olin is not there.

Wowhead: https://www.wowhead.com/quest=34462/winds-of-change#videos:id=40096

**Comment by cgsnascar** [comment]
A note on this, I see him there, shows the quest icon like I need to save him, but can't

**Comment by Deathrift991** [comment]
This needs to be a priority fix, we can't actually progress through the Frostfire Ridge questlines with this bug.
