### ISSUE TITLE
Object - [Garrison cache: 236916]

### ISSUE THREAD

**Issue by SimeonGavrilov** [Hazor-Hellscream/Project-Hellscream-Info#275]
Missing object-model, as a result - no interaction with object. (Horde garrison)

Priority: Critical

Wowhead:
(https://ptr.wowhead.com/object=236916/garrison-cache)

**Comment by Hazor-Hellscream** [comment]
If you /reload or logout and in it will load the [Garrison cache: 236916] in your garrison.

**Comment by SimeonGavrilov** [comment]
Update:

cache now is visible and work, but has wrong model (its has alliance model for horde)
