### ISSUE TITLE
Follower - [Tormmok: 193]

### ISSUE THREAD

**Issue by SimeonGavrilov** [Hazor-Hellscream/Project-Hellscream-Info#279]
No interaction with follower. NPC is hostile.

Priority: Low

Wowhead:
(https://ptr.wowhead.com/follower=193/tormmok)
Follower's quest:
(https://ptr.wowhead.com/quest=36037/a-centurion-without-a-cause)

**Comment by Hazor-Hellscream** [comment]
6.0 Blizzlike Guide wowhead:

You'll found him at 44.9, 86.9 in Gorgrond.

He'll probably be fighting some mobs, and you'll see him as hostile (red), though you won't be able to attack him.

Just kill wave after wave of mobs (it may take a few) until Woodfist appears. When you kill Woodfist, Tormmok will turn to friendly (green) and after a little talk, he'll offer you the quest to recruit him.
