### ISSUE TITLE
Spell - Crimson Scourge (Blood DK)

### ISSUE THREAD

**Issue by Rakarth802** [Hazor-Hellscream/Project-Hellscream-Info#284]
http://prntscr.com/r6m4mg

Currently makes the spell free but does not reset the rune CD timer on the ability when it procs like it's supposed to.

Prio: High.

**Comment by Firoqt** [comment]
Not a bug, per https://wow.gamepedia.com/Crimson_Scourge patchnotes. Cooldown reset wasn't implemented until Legion.
