### ISSUE TITLE
Quest - [The Taste Test: 12645]

### ISSUE THREAD

**Issue by garw4** [Hazor-Hellscream/Project-Hellscream-Info#29]
Quest - [The Taste Test: 12645]
Zone: Sholazar Basin
Completable: NO

You offer sample of a drink(38697) to 3 npcs. The interaction with 2 of them works but with the 3rd npc Tamara Wobblesprocket(28568) it doesn't.

Priority:
Medium

WoW Head Link:
[https://www.wowhead.com/quest=12645/the-taste-test](url)

**Comment by Goretech** [comment]
Working, can be closed.
