### ISSUE TITLE
Quest- [Snatch 'n' Grab:36287]

### ISSUE THREAD

**Issue by Holyblaster** [Hazor-Hellscream/Project-Hellscream-Info#291]
Info: can not interact
https://www.wowhead.com/quest=36287/snatch-n-grab
![WoWScrnShot_022320_225139](https://user-images.githubusercontent.com/60840202/75152565-c727cb80-5722-11ea-8abe-e3c572213d1c.jpg)

**Comment by EyalMK** [comment]
Fixed and Tested
