### ISSUE TITLE
Dungeon: Scarlet Monastery

### ISSUE THREAD

**Issue by Goretech** [Hazor-Hellscream/Project-Hellscream-Info#308]
No archievement for killing High Inquisitor Whitemane.
Cant enter room where High Inquisitor Fairbanks is.

https://classic.wowhead.com/scarlet-monastery

**Comment by SimeonGavrilov** [comment]
upd:
she has 68 lvl
![WoWScrnShot_041420_195556](https://user-images.githubusercontent.com/52416849/79246744-a6f6cc00-7e8a-11ea-80a1-3e9e0678ce3f.jpg)
And no achivement
![WoWScrnShot_041420_195845](https://user-images.githubusercontent.com/52416849/79246762-ac541680-7e8a-11ea-9e0e-e56e18966820.jpg)

**Comment by EyalMK** [comment]
This version of Scarlet Monastery has been deprecated and implemented the new MoP version instead.
The report is not relevant anymore and therefore won't fix. Closed.
