### ISSUE TITLE
Zone- [Draenor]

### ISSUE THREAD

**Issue by 601bukaj** [Hazor-Hellscream/Project-Hellscream-Info#321]
Information:
A lot of NPCs do not offer their quests like for example Cordana Felsong does not offer Meet Us at Starfall Outpost.

**Comment by Firoqt** [comment]
Are you sure you meet the requirements for that particular quest? it requires you to be a level 94.
https://wow.gamepedia.com/Meet_Us_at_Starfall_Outpost

**Comment by 601bukaj** [comment]
I thought it was normal shadowmoon valley quest line as WoWhead shows it's level 90, my bad.
