### ISSUE TITLE
Quest from garrison Bulletin board

### ISSUE THREAD

**Issue by 601bukaj** [Hazor-Hellscream/Project-Hellscream-Info#338]
Information:
Quests offered from the Bulletin board in garrison are also offered from Bodrick Grey, which duplicates them.

**Comment by Firoqt** [comment]
Working as intended. This is blizzlike - see the quest https://www.wowhead.com/quest=35556/the-secrets-of-gorgrond for example. Can be picked up by the board and Bodrick Grey.
