### ISSUE TITLE
Spell - [Storm, Earth, and Fire: 137639]

### ISSUE THREAD

**Issue by 601bukaj** [Hazor-Hellscream/Project-Hellscream-Info#357]
Information:
Spawned 'clones' do not disappear after killing an enemy and if canceled they stay with player and attack anything and follow him

Demonstration:
https://youtu.be/9ftCICiVBkQ

WoWhead link:
https://www.wowhead.com/spell=137639/storm-earth-and-fire

**Comment by 601bukaj** [comment]
Spawning fire spirit (second spirit) seems to crash the server

**Comment by 601bukaj** [comment]
Fire Spirit now starts attacking its target but after trying to mimic players attacks crashes the server

**Comment by Hazor-Hellscream** [comment]
Disabled in world db until fixed.

**Comment by Hazor-Hellscream** [comment]
fixed 0.1.5
