### ISSUE TITLE
Quest - A Gronnling Problem

### ISSUE THREAD

**Issue by szentigrad3** [Hazor-Hellscream/Project-Hellscream-Info#361]
can't complete as the gronnlings dont spawn
https://www.wowhead.com/quest=34592/a-gronnling-problem

**Comment by EyalMK** [comment]
Working as intended. (Still haven't implemented phasing for pre-garrison quests and therefore the telescope hackfix was made as a temporary fix). The gronnlings are in a different phase and currently the quest chain is in development.
