### ISSUE TITLE
Quest: [The Mist Isn't Listening: 12538]

### ISSUE THREAD

**Issue by garw4** [Hazor-Hellscream/Project-Hellscream-Info#39]
Quest: [The Mist Isn't Listening: 12538]
Zone: Sholazar Basin
Completable: NO

Mistwhisper NPCs are targetable but you can't attack them.

Priority:
Medium

WoW Head Link:
[https://www.wowhead.com/quest=12538/the-mist-isnt-listening](url)

**Comment by Goretech** [comment]
Working, can be closed.
