### ISSUE TITLE
Battle horn-item

### ISSUE THREAD

**Issue by Goretech** [Hazor-Hellscream/Project-Hellscream-Info#406]
This should have low droprate from pandaria rares, dropped for me from first kill of a mob in timeless isle.

https://www.wowhead.com/item=86565/battle-horn

**Comment by EyalMK** [comment]
Weird. In the database the chance is 0.5% from https://www.wowhead.com/npc=72875/ordon-candlekeeper as intended and 20% from Blackhoof. Can you test this again and see if you got lucky?

**Comment by Goretech** [comment]
Tested again, i guess i was lucky because im not getting the item on another character, so issue can be closed.

**Comment by EyalMK** [comment]
Thanks.
