### ISSUE TITLE
Spell - Beacon of Light and Beacon of Faith

### ISSUE THREAD

**Issue by Saesuri** [Hazor-Hellscream/Project-Hellscream-Info#427]
![image](https://user-images.githubusercontent.com/9422623/76176905-29f07c80-6191-11ea-9de1-6570dfed6730.png)
You should not be able to cast Beacon of Light on a target affected by Beacon of Faith.

Priority:
High

**Comment by Saesuri** [comment]
What i meant is, you are not supposed to have 2 beacons on the same target, and the 'fix' you did was the complete opposite.

This was the behavior before the fix: If you cast Beacon of Light and tried to cast Beacon of Faith on the same target, you couldn't, and that was correct.

The bug: It was possible to cast Beacon of Faith and THEN cast Beacon of Light.
What is happening after the 'fix': Doesn't matter the order in which you cast the Beacons, you can always have both at the same time, and that is incorrect. You should never be able to have 2 beacons on the same target.

Correct behaviour: You shouldn't be able to have 2 beacons on the same target regardless of cast order, both beacons should check if the target already has another beacon before casting.

**Comment by Hazor-Hellscream** [comment]
working in 0.1.6
