### ISSUE TITLE
Spell - Renewing Mist

### ISSUE THREAD

**Issue by Saesuri** [Hazor-Hellscream/Project-Hellscream-Info#432]
https://clips.twitch.tv/HedonisticFunBoarMVGame

If all targets already have Renewing Mist applied on them, the spell should refresh the buff with the lowest duration, it currently only checks if the target has a buff.

Priority:
High

**Comment by Firoqt** [comment]
Pushed a fix for this, needs to be tested, but code states:  First check if every target it can find that exists(and can be given the buff) already has the buff, if not every target has the buff, get rid of the targets who do from the list. Then, find the person with the lowest health out of all the targets who don't have the buff. Once it finds it, cast it on that target.
However, if every target DOES have the buff, find the person with the shortest duration left on the buff, and rebuff them.

**Comment by Saesuri** [comment]
Fixed
