### ISSUE TITLE
Spell - Eminence

### ISSUE THREAD

**Issue by Saesuri** [Hazor-Hellscream/Project-Hellscream-Info#433]
https://clips.twitch.tv/PatientHandsomePepperDerp

1 - Eminence is healing too much, not sure if it should count both the monk's passive and the statue passive. But there are a lot of numbers there, also its generating a lot of healing spheres.
2 - Eminence is only healing the monk, it should heal other people too.

Priority:
High

**Comment by Firoqt** [comment]
Cannot replicate second issue on local, first issue is blizzlike from what I can see. I removed Spinning Crane Kick from a spell that proc's Eminence, but according to this: https://wow.gamepedia.com/Eminence_(monk_ability) it does proc from Autoattacks. A lot of the numbers are coming from Monk Mastery.
