### ISSUE TITLE
Dying in Tanaan jungle

### ISSUE THREAD

**Issue by Goretech** [Hazor-Hellscream/Project-Hellscream-Info#434]
When you release spirit, atleast if you die on Kazzak, you end up underground in Scuttler´s Coast.
You fall down and keep falling everytime you login again and die. 45. 82. coordinates.

**Comment by Hazor-Hellscream** [comment]
Graveyard spawn location is under the map by like 2 or 3 in y value.

**Comment by EyalMK** [comment]
Tanaan Jungle is currently under development and will not be released in the near future and will not be accessible until progression at which point it will be long worked on.
Therefore - This issue will be closed until Tanaan is in a testing realm.
