### ISSUE TITLE
Spell - [Soulstone: 20707]

### ISSUE THREAD

**Issue by 601bukaj** [Hazor-Hellscream/Project-Hellscream-Info#451]
Issue:
Casting Soulstone gives the player 60s buff to be resurrected (160029), even if the player is alive. Soulstone works without any more problems
![s](https://user-images.githubusercontent.com/60825730/76457678-834aec80-63d9-11ea-9be5-613447ee7a10.PNG)

Wowhead:
https://www.wowhead.com/spell=20707/soulstone
https://www.wowhead.com/spell=160029/resurrecting

**Comment by Nyr97** [comment]
Pre-fix behaviour:

When using Soulstone on an alive player, he would gain both the Soulstone effect and Resurrecting buff. When using Soulstone on a dead player, he would instantly revive with no chance to accept the resurrection, which may lead to unfortunate timings during PvE or PvP encounters.

Current behaviour:

When using Soulstone on an alive player, he gains the Soulstone effect only. When using Soulstone on a dead player, he receives the tab option to accept the resurrection. Changes will be applied on next update.
