### ISSUE TITLE
Spell - [Demonic Circle: Teleport: 48020]

### ISSUE THREAD

**Issue by 601bukaj** [Hazor-Hellscream/Project-Hellscream-Info#455]
Issue:
After your Demonic circle disappears you can still use the teleport, even thou you don't get ported. It should check if you still have the circle summoned

Wowhead:
https://www.wowhead.com/spell=48020/demonic-circle-teleport

**Comment by Goretech** [comment]
Not fixed, the button stays usable, and there is no visual of the demonic circle.

**Comment by Goretech** [comment]
Note on my comment, if you relog the button is not usable anymore.

**Comment by Goretech** [comment]
Visual is now working.

**Comment by Firoqt** [comment]
If this is still a bug, it's because it wasn't applied. I fixed this a while ago.
