### ISSUE TITLE
[Quest] - Balanced Perspective

### ISSUE THREAD

**Issue by szentigrad3** [Hazor-Hellscream/Project-Hellscream-Info#460]
https://www.wowhead.com/quest=29784/balanced-perspective >
can't pickup this quest after doing the pre-quests >
https://www.wowhead.com/quest=29779/the-direct-solution
https://www.wowhead.com/quest=29780/do-no-evil
https://www.wowhead.com/quest=29781/monkey-advisory-warning
https://www.wowhead.com/quest=29782/stronger-than-bone

**Comment by Hazor-Hellscream** [comment]
Fixed on next restart added missing values to creature_queststarter.
