### ISSUE TITLE
Spell - [Eminence: 126890] / [Eminence (Statue): 117895] and [Spinning Crane Kick: 101546] Interaction

### ISSUE THREAD

**Issue by Sanaka3** [Hazor-Hellscream/Project-Hellscream-Info#465]
Spinning Crane Kick doesn't trigger either Eminence when in Stance of the Spirited Crane (id 154436) when it should, as Icy-Veins guide says (link below to archive of 6.2.2 guide):
http://web.archive.org/web/20150911233050/http://www.icy-veins.com/wow/mistweaver-monk-pve-healing-rotation-cooldowns-abilities#sec-1-2

**Comment by Firoqt** [comment]
https://www.icy-veins.com/forums/topic/2619-a-guide-to-fistweaving-hitting-it-where-it-counts/ This guide states that it DOESNT proc Eminence, so unless someone can show me conclusive proof, it will remain like this.

**Comment by Sanaka3** [comment]
Adding a video I sent in discord confirming it in action, as reference.
https://www.youtube.com/watch?v=BMqcEp4tX-k

**Comment by Nyr97** [comment]
As stated, it shouldn't proc Eminence as the spell itself has a healing component on it.
