### ISSUE TITLE
Spell/Core Mechanic - Causing Crashes

### ISSUE THREAD

**Issue by Saesuri** [Hazor-Hellscream/Project-Hellscream-Info#467]
If a player casting a damaging spell while in combat gets interrupted by an unusual way, the server crashes. Let me give you a few examples.

First one is through spiritwalker's grace: Cast spiritwalkers grace, and when the spell is about to end, you cast lightning bolt on the dummy for example(need to be in combat). If you dont finish the spell before the buff fades, the server crashed, because the spell got interrupted in an unusual way.
Second one is through death grip/mass grip from dk: just have someone be in combat casting damagin spells, and interrupt their cast with death grip/mass grip and the server crashes.
Third one is through ice floes: probably the easiest one to replicate, i recommend you test using this method. 
1. Step one: cast ice floes
2. Step two: be in combat
3. Step three: cast blizzard on dummy
4. Step four: cast blizzard again on the dummy
5. Step five: the server has crashed

Remember you need to be moving, so the spell gets interrupted once you no longer can "cast while moving".

This is probably the cause of a lot of crashes during testing time.

Priority:
Very very critical.

**Comment by Hazor-Hellscream** [comment]
[Spiritwalker's Grace] - works fine with  [Elemental Blast]  [Lava Burst] now without issues.

Testing others now.

**Comment by Hazor-Hellscream** [comment]
#https://github.com/Hazor-Hellscream/Project-Hellscream-Core/commit/bbf14cae28c0265eadec24a54649b8de4342b77b

**Comment by Hazor-Hellscream** [comment]
[Ice Floes] + Blizzard working fine now.

**Comment by Hazor-Hellscream** [comment]
[Spiritwalker's Grace] ends while casting  [Elemental Blast] it will crash but fixed all other spells being interrupted right.

**Comment by Hazor-Hellscream** [comment]
#https://github.com/Hazor-Hellscream/Project-Hellscream-Core/commit/395cfb88e3a08b4491a99cdcb4700ab39e92e6f1

Should be working fine now

**Comment by Firoqt** [comment]
Fixed all issues here.
