### ISSUE TITLE
Spell - Fists of Fury

### ISSUE THREAD

**Issue by Saesuri** [Hazor-Hellscream/Project-Hellscream-Info#493]
Fists of Fury doesnt channel the whole ability, it only does one tick of damage. Possibly broken after this fix https://github.com/Hazor-Hellscream/Project-Hellscream-Info/issues/467.

Priority: High

**Comment by Sanaka3** [comment]
This was affecting Blizzard as well. Other channeled spells have to be tested for this bug as well.
