### ISSUE TITLE
Quest - [Westfall Stew: 26241]

### ISSUE THREAD

**Issue by ShaldarWoW** [Hazor-Hellscream/Project-Hellscream-Info#5]
Fleshrippers can't be looted to obtain Stringy Fleshripper Meat.

There's a workaround by focusing on killing Young Fleshrippers instead.

Priority:
Low

WoW Head Link:
(https://www.wowhead.com/quest=26241/westfall-stew)

**Comment by 601bukaj** [comment]
Fixed

**Comment by ShaldarWoW** [comment]
Can confirm, fixed.
