### ISSUE TITLE
Client - Crash on Game-Start

### ISSUE THREAD

**Issue by cnachtigall1991** [Hazor-Hellscream/Project-Hellscream-Info#503]
Hey,
after downloading the client (Full and Mini), I tried to start the 'Project\ Hellscream\ x64.exe' and I always get a popup window.

**Image of the popup:** https://ibb.co/jV3bF7z

Tried on Full- and Mini-Client, also tried to run as Administrator.

**My speccs:**
Win10Pro x64, Version 1909
i5-6600k
16 GB RAM
GTX 970

**Comment by Simplexsys** [comment]
[Fix.zip](https://github.com/Hazor-Hellscream/Project-Hellscream-Info/files/4370228/Fix.zip)

Step 1 - Download the file attached.

Step 2 - Extract the the file to your Hellscream folder overwrite anything it asks you to.

Step 3 - Right click, properties your Hellscream Folder and turn read only off once again.

Step 4 - Run Project Hellscream x64.exe as administrator, should be working fine now.
