### ISSUE TITLE
npc=5809 Untargetable

### ISSUE THREAD

**Issue by Simplexsys** [Hazor-Hellscream/Project-Hellscream-Info#510]
npc=5809 is untargetable for reasons unkown. See attached gif. 

![Target Error NPC 5809](https://user-images.githubusercontent.com/7108223/77267956-3a7a1a00-6c9c-11ea-90a6-865f777185cf.gif)

**Comment by EyalMK** [comment]
Fixed a while ago. It was the wrong spawn point.
