### ISSUE TITLE
Spell Id: 66 [ Mage: Invisibility ]

### ISSUE THREAD

**Issue by Simplexsys** [Hazor-Hellscream/Project-Hellscream-Info#526]
Mage Spell - Invisibility: id 66 is currently not working as intended. It allows the player to remain unseen by enemy NPC's. See attached gif. Persists through /reload, but relogging resolves the issue.
![Invisibility Bug LOSSY](https://user-images.githubusercontent.com/7108223/77428830-a2318180-6dd0-11ea-8f51-e6bee6a6fa02.gif)

**Comment by Firoqt** [comment]
Was able to duplicate this a bunch of times, then .unaura all, now I can't duplicate it for the life of me. Even with a new character. Let me know if you can find a cause for this.
