### ISSUE TITLE
Map Issue: Garrison - Frostwall Mines interior.

### ISSUE THREAD

**Issue by Simplexsys** [Hazor-Hellscream/Project-Hellscream-Info#527]
Frostwall Mines missing causing player to fall through the world. Cannot release on death, or use conventional logout/exit method, alt F4 causes client to show as not responding requiring a 'close anyway' dialogue box. Persists through a client restart, cache clear and /reload. Upon restarting the client and logging in to affected character, you are re-spawned without penalty. See attached GIF's.
![Frostwall Mines Bug Pt1](https://user-images.githubusercontent.com/7108223/77430171-aa8abc00-6dd2-11ea-99b5-00cc6469c1bb.gif)
![Frostwall Mines Bug Pt2](https://user-images.githubusercontent.com/7108223/77430265-ca21e480-6dd2-11ea-9fb3-7e3a822a977f.gif)

**Comment by Hazor-Hellscream** [comment]
#414
