### ISSUE TITLE
fly master missing

### ISSUE THREAD

**Issue by ggrimlen** [Hazor-Hellscream/Project-Hellscream-Info#540]
fly master missing
![WoWScrnShot_032520_132730](https://user-images.githubusercontent.com/62609915/77533597-d627a800-6e9f-11ea-90b0-e102a245e271.jpg)

**Comment by Hazor-Hellscream** [comment]
npc=43045/james-stillair fixed on last restart.

![image](https://user-images.githubusercontent.com/53961554/77830396-cea02180-7173-11ea-9894-4f5af30e2023.png)
