### ISSUE TITLE
Quest: Club Foote

### ISSUE THREAD

**Issue by Blackoutx** [Hazor-Hellscream/Project-Hellscream-Info#546]
There is no dialogue option with chief engineer foote at which point you would club him and be able to search his pockets and loot the item 

The quest is completable however if you simply kill the npc it will drop the ship schematics, it is however not how the quest is supposed to work.

https://www.wowhead.com/quest=14034/club-foote#comments

**Comment by EyalMK** [comment]
Fixed and tested. Completely Blizzlike.
