### ISSUE TITLE
Combat Bug

### ISSUE THREAD

**Issue by Blackoutx** [Hazor-Hellscream/Project-Hellscream-Info#553]
If you run by an aggressive mob and dont kill it but let it chain reset, sometimes it will just keep you in combat forever, this could be an issue with pets, or just ranged attack style npcs. but it has happened almost a dozen times while i was questing forcing me to relaunch the game to clear combat. 

In regards to the pet theory, i've tried dismissing pet when i run far away and that doesn't seem to drop combat either.

**Comment by Hazor-Hellscream** [comment]
#573

**Comment by Dognibba** [comment]
My experience: every mob that kills me while my dot is on them, keep camping at my corpse until my dot runs out, then goes back and resets.

**Comment by EyalMK** [comment]
Fixed Thanks to @Nyr97  - Please test and let us know if the issue comes up once again.
