### ISSUE TITLE
Damage Over Time spells

### ISSUE THREAD

**Issue by Dognibba** [Hazor-Hellscream/Project-Hellscream-Info#572]
Tested on balance druid, with spell https://ptr.wowhead.com/spell=8921/moonfire When i refresh it, the spell's tick timer is reset.

How it should work (excerpt from wowpedia): 
Also as of patch 4.0.1, DoTs no longer can be 'clipped'. Previously, if a DoT was refreshed before it had expired, the tick timer was reset, causing a delay of up to double the normal time between ticks between the last tick that occurred and the first tick of the refreshed DoT. **Now, the tick timer is constant. If a DoT is refreshed before it expires, the duration of the DoT will be extended by up to the full normal duration of the DoT, and ticks will continue to occur at the prior interval.** Between patches 4.0.1 and 6.0.1, this functionality only allowed DoTs to be "clipped" by a single tick before duration was wasted, requiring DoTs to be refreshed between the second-to-last and the last tick to maintain uninterrupted DoT ticks while optimizing duration gain. Patch 6.0.1 extended this period to 30% of the DoT's normal duration. For example, a 15 second DoT can be extended when it has less than 4.5 seconds remaining at no duration loss (the full normal duration is added to the remaining duration). This also applies to many short-duration buffs like  [Slice and Dice].

**Comment by Dognibba** [comment]
oh and of course i forgot healing over time spells have the same problem. very critical issue indeed

**Comment by Nyr97** [comment]
- [ ] Dots and Hots are no longer clipped.
- [ ] Now, the tick timer is constant. If a DoT is refreshed before it expires, the duration of the DoT will be extended by up to 30% of its duration, and ticks will continue to occur at the prior interval.
