### ISSUE TITLE
Quest - [Thunderhorn totem: 24441]

### ISSUE THREAD

**Issue by SimeonGavrilov** [Hazor-Hellscream/Project-Hellscream-Info#575]
Quest-NPC is missing on whole location

Priority: Medium

Wowhead:
(https://ptr.wowhead.com/quest=24441/thunderhorn-totem)
Missing NPC:
(https://ptr.wowhead.com/npc=2959/prairie-stalker)

**Comment by EyalMK** [comment]
NPCs already exist.
