### ISSUE TITLE
Quest - [A Daughter's Embrace: 25046]

### ISSUE THREAD

**Issue by szentigrad3** [Hazor-Hellscream/Project-Hellscream-Info#580]
once you accept the quest you are meant to get Lilian Voss, instead you get Vengeful Forsaken. Once you reach High Priest Voss you have to kill him stead of Lillian Triggering a scene(refer to video) > https://www.youtube.com/watch?v=6GIY8GuWp-I > https://www.wowhead.com/quest=25046/a-daughters-embrace

**Comment by EyalMK** [comment]
Scripted - Test this please.
[*] - To do, implement the path for when Lilian kills her father and jumps on wall then falls down and walks outside the tower.

**Comment by EyalMK** [comment]
Tested and fixed. Completely blizzlike. Closed
