### ISSUE TITLE
Command - /fear

### ISSUE THREAD

**Issue by ShaldarWoW** [Hazor-Hellscream/Project-Hellscream-Info#62]
The command /fear animation doesn't stop after moving.
The workaround is to use other commands to reset the basic walking and idle animations, such as /laugh.

Priority:
Low

**Comment by AI38** [comment]
Happened to me aswell when i used eviscerate as a rogue, got stuck in animation until i got killed, using any sort of animated emote didn't fix the problem unlike fear.

**Comment by ShaldarWoW** [comment]
Fixed animations getting stuck after moving since last update.
