### ISSUE TITLE
NPC - [Springvale spawn stalker: 50611]

### ISSUE THREAD

**Issue by SimeonGavrilov** [Hazor-Hellscream/Project-Hellscream-Info#639]
NPC is Attacking players from the invisibility. (auto-attack about 1k dmg). Doesn't have model, can't be killed

Priority: Hight

Wowhead:
(https://ru.wowhead.com/npc=50611/springvale-spawn-stalker)

**Comment by EyalMK** [comment]
Fixed a while ago.
