### ISSUE TITLE
Zone - [Darkshire, Duskwood]

### ISSUE THREAD

**Issue by RemoteDefinition** [Hazor-Hellscream/Project-Hellscream-Info#659]
There is an untargetable Cult of the Damned NPC that is standing near the Inn and the City Hall. He can target players and kill them if they don't escape fast enough.

He shouldn't be there at all.

**Comment by Hazor-Hellscream** [comment]
Just fixed it then Creature abercrombie removed from there as his location is not there nor is that his npc id.
![image](https://user-images.githubusercontent.com/53961554/78359352-477dfe00-75f8-11ea-9170-9e673a8ba01a.png)
