### ISSUE TITLE
New way TBC

### ISSUE THREAD

**Issue by Nirno96** [Hazor-Hellscream/Project-Hellscream-Info#660]
Find a new way to TBC

![WoWScrnShot_040320_125646](https://user-images.githubusercontent.com/63050534/78348392-9dc45000-75aa-11ea-81f9-3f57b64bcf91.jpg)
![WoWScrnShot_040320_123712](https://user-images.githubusercontent.com/63050534/78348402-a026aa00-75aa-11ea-870d-940451792d10.jpg)

**Comment by Hazor-Hellscream** [comment]
![image](https://user-images.githubusercontent.com/53961554/78357336-a0e42e00-75f4-11ea-9227-0f4111556c45.png)
Fixed on live 1-60 now.
