### ISSUE TITLE
Quest "You are Rakh'likh demon"

### ISSUE THREAD

**Issue by Nirno96** [Hazor-Hellscream/Project-Hellscream-Info#661]
https://classic.wowhead.com/quest=3628/you-are-rakhlikh-demon
Deathly Usher haven't the dialog box.
![WoWScrnShot_040320_133003](https://user-images.githubusercontent.com/63050534/78351296-3b218300-75af-11ea-8fed-82317dd5909c.jpg)

**Comment by EyalMK** [comment]
Fixed a while ago.
