### ISSUE TITLE
Dodge

### ISSUE THREAD

**Issue by Nirno96** [Hazor-Hellscream/Project-Hellscream-Info#676]
Items don't give dodge on proto paladin.
![WoWScrnShot_040220_204023](https://user-images.githubusercontent.com/63050534/78374528-8c903900-75d4-11ea-864b-c1f7b5310f9a.jpg)
![WoWScrnShot_040220_204006](https://user-images.githubusercontent.com/63050534/78374563-8dc16600-75d4-11ea-8192-0e561506479e.jpg)

**Comment by Hazor-Hellscream** [comment]
Once you have items equipped you need to relog or /reload to show it.
