### ISSUE TITLE
Discord link?

### ISSUE THREAD

**Issue by Boome01** [Hazor-Hellscream/Project-Hellscream-Info#681]
Hello,
this is not any bug report, but I couldn't contact any eligible person since I´m just downloading client.
Discord link is nowhere to be found on website.
If you could be so nice and provide it anywhere on website it would be nice!

Have a nice evening.

**Comment by Naiizu** [comment]
Ok, I have been searching through all pages around that had to do atleast something with this project and found working link: https://discordapp.com/invite/a4AQf2z
