### ISSUE TITLE
Quest - [Lou's Parting Thoughts: 26232]

### ISSUE THREAD

**Issue by ShaldarWoW** [Hazor-Hellscream/Project-Hellscream-Info#7]
Quest - [Lou's Parting Thoughts: 26232]

![unknown](https://user-images.githubusercontent.com/60824117/74090361-bcc2cc00-4aaa-11ea-8295-e52e4474ef02.png)

The thugs don't perform the required dialog to progress the quest.

Priority: 
Low

WoW Head Link:
(https://www.wowhead.com/quest=26232/lous-parting-thoughts)

**Comment by trilumx2** [comment]
unable to turn in

**Comment by Rorhn** [comment]
Currently can kill the thugs (without the dialogue) for credit. However the turn-in area doesn't phase properly so the quest cant' be turned in.

**Comment by EyalMK** [comment]
Fixed.
