### ISSUE TITLE
Dungeon : Lower Blackrock Spire

### ISSUE THREAD

**Issue by cgsnascar** [Hazor-Hellscream/Project-Hellscream-Info#747]
The portal to get into the dungeon Lower Blackrock Spire doesn't exist.

![Annotation 2020-04-04 195741](https://user-images.githubusercontent.com/14172411/78463753-a00fd280-76ae-11ea-950c-136f193de37b.png)

![Annotation 2020-04-04 195904](https://user-images.githubusercontent.com/14172411/78463768-c7ff3600-76ae-11ea-892e-4e98d7b7c8ed.png)

**Comment by EyalMK** [comment]
Fixed by Hazor.
