### ISSUE TITLE
NPC - [Andorhal Deathguard: 44331]

### ISSUE THREAD

**Issue by Rorhn** [Hazor-Hellscream/Project-Hellscream-Info#748]
https://www.wowhead.com/npc=44331/andorhal-deathguard

Mob hits obscenely too hard/fast.

**Comment by EyalMK** [comment]
This is not a bug, these Deathguards are supposed to hit 'hard' and their attacks are every 2 seconds.
If you're still convinced this is bugged then please by all means come up with proof and talk to me in Discord (Ely). 

Improved Andorhal Deathguards in this commit - Set correct flags, set Thrash aura and set equipment ID.
