### ISSUE TITLE
NPC - [Death's Step Miscreation: 45444]

### ISSUE THREAD

**Issue by Rorhn** [Hazor-Hellscream/Project-Hellscream-Info#749]
https://www.wowhead.com/npc=45444/deaths-step-miscreation

Currently this mob has no cast time for Blight Bomb, it should be 5s. 

It should only be cast when the mob reaches a certain health threshold, I believe 20% but I'm not positive.

**Comment by EyalMK** [comment]
Fixed. Should cast Blight Bomb at 15% HP now. Please test :)
