### ISSUE TITLE
Quest - [Out of Place: 27961]

### ISSUE THREAD

**Issue by Rorhn** [Hazor-Hellscream/Project-Hellscream-Info#754]
https://www.wowhead.com/quest=27961/out-of-place

Currently the ash chickens cannot be collected, they just disappear.

**Comment by EyalMK** [comment]
Reworked this quest, please test and let me know how it goes.

**Comment by szentigrad3** [comment]
does as first reported, test as patch 0.1.7

**Comment by EyalMK** [comment]
Fixed and tested. Closed.
