### ISSUE TITLE
Quest - [Done Nothing Wrong: 28172]

### ISSUE THREAD

**Issue by Rorhn** [Hazor-Hellscream/Project-Hellscream-Info#756]
https://www.wowhead.com/quest=28172/done-nothing-wrong

Interacting with the drakes doesn't properly count towards quest completion. They just disappear.

**Comment by EyalMK** [comment]
Reworked. Fixed for Alliance and Horde, please test.

**Comment by EyalMK** [comment]
Fixed and tested. Closed.
