### ISSUE TITLE
Class - [Rogue: General]

### ISSUE THREAD

**Issue by Rorhn** [Hazor-Hellscream/Project-Hellscream-Info#757]
Dual Spec costs more than 10g, I'm unsure of how much it does cost. However trainers in SW and IF both require more than 128g to teach it to you.

![image](https://user-images.githubusercontent.com/26292278/78514542-8d150500-7777-11ea-8c3b-d43438e47016.png)

**Comment by Hazor-Hellscream** [comment]
Fixed on next restart to 10g.
