### ISSUE TITLE
Quest - [Even thieves get hungry: 26235]

### ISSUE THREAD

**Issue by SimeonGavrilov** [Hazor-Hellscream/Project-Hellscream-Info#758]
Quest-NPC are missing.

Priority: Medium

Wowhead:
(https://ptr.wowhead.com/quest=26235/even-thieves-get-hungry)
NPCs:
(https://www.wowhead.com/npc=42594/orgrimmar-thief)

**Comment by EyalMK** [comment]
NPCs are spawned, they're stealthed. Watch https://www.wowhead.com/quest=26235/even-thieves-get-hungry#videos:id=97120 for reference.

**Comment by SimeonGavrilov** [comment]
a'm waided about 10 min, i don't find NPC in same plase. They are 10 lvl, i must see them even in invisibility. And, ofc, i tested it with help of my AoE
![WoWScrnShot_050820_173734](https://user-images.githubusercontent.com/52416849/81411479-75a0b180-9153-11ea-9be6-7c5745933e2f.jpg)

![WoWScrnShot_050820_173737](https://user-images.githubusercontent.com/52416849/81411465-71749400-9153-11ea-8061-f58ae1002347.jpg)

**Comment by SimeonGavrilov** [comment]
and, ofc, tested another places, i didn't find any of them

**Comment by EyalMK** [comment]
Fixed and tested. Closed.
