### ISSUE TITLE
Quest - [The Wakening] : 24960

### ISSUE THREAD

**Issue by Daz9999** [Hazor-Hellscream/Project-Hellscream-Info#762]
Undead starting zone quest where you have to talk with 3 npcs.

they have that rp text clickable stuff, thing is that whenever i click the last text it wont complete it

**Comment by EyalMK** [comment]
Fixed - currently do-able but not the blizzlike way. The npcs themselves run the path instead of the spells used to summon the same npcs at the same location to do the job (used to put a smaller respawn timer for the npcs) - not a priority.

**Comment by Goretech** [comment]
No quest npcs and minimap is showing wrong.
![WoWScrnShot_042320_095931](https://user-images.githubusercontent.com/60852022/80068967-2d757280-8549-11ea-81f7-2ab34f040951.jpg)

**Comment by EyalMK** [comment]
Reworked the entire script and made it completely blizzlike. Closed.
