### ISSUE TITLE
Spell - Chi Wave

### ISSUE THREAD

**Issue by Saesuri** [Hazor-Hellscream/Project-Hellscream-Info#764]
Chi wave should not break the cc on targets affected by Paralysis/freezing trap/blind/sap, in general ccs that break with damage. 

If Chi Wave is already mid-air when the target is cced, then it should break the cc.
If you cast Chi Wave after the target is cced, it should _not_ break the cc.

proof: http://www.skill-capped.com/forums/showthread.php?29749-Zen-sphere-vs-chi-wave-3-s

"Chi Wave can certainly cause issues with breaking CC, the best way to work around this is to practice not using it when your teammate is calling out his CC or about to get CC, wait till he lands his CC before casting it (Chi wave will ignore the CC'd target, it only breaks a trap or something if the chi wave particle is mid-air traveling to the target)."

priority: high

**Comment by Firoqt** [comment]
Fixed.
