### ISSUE TITLE
NPC - [Gomegaz: 41166]

### ISSUE THREAD

**Issue by szentigrad3** [Hazor-Hellscream/Project-Hellscream-Info#773]
skin of gomegaz is wrong he is meant to be a core hound > https://www.wowhead.com/npc=41166/gomegaz > https://puu.sh/FuS9m/f582162f77.jpg

**Comment by SimeonGavrilov** [comment]
![image](https://user-images.githubusercontent.com/52416849/78975544-5ea37b00-7b25-11ea-90e8-6302a9b6d7b1.png)
NPC has wrong model.

**Comment by szentigrad3** [comment]
not fixed > https://puu.sh/Fwq77/59c432e721.jpg

**Comment by EyalMK** [comment]
https://puu.sh/FwXPB/df89c8886f.jpg - Fixed on my end. If this isn't working after 0.1.7a - @ me in Discord or re-open.

Closed.
