### ISSUE TITLE
Raid-NPC - [Majordomo Executus: 12018]

### ISSUE THREAD

**Issue by SimeonGavrilov** [Hazor-Hellscream/Project-Hellscream-Info#774]
NPC is doubled. So, u can summ (https://ptr.wowhead.com/npc=11502/ragnaros) twice

Priority: Critical

Wowhead:
(https://ptr.wowhead.com/npc=12018/majordomo-executus)

**Comment by EyalMK** [comment]
Doubled as in spawned twice? because the data in DB indicates that there's only one spawned.

**Comment by SimeonGavrilov** [comment]
Yday was same. There was two bosses. And yes, they are spawned twice. But first time when we enter in MC, was just one Majordomo.  I will do screenshots today if them will be twice.

**Comment by SimeonGavrilov** [comment]
![image](https://user-images.githubusercontent.com/52416849/79001830-4735b380-7b60-11ea-847b-7510e65c5e01.png)

**Comment by Hazor-Hellscream** [comment]
Fixing it now mate.

**Comment by Hazor-Hellscream** [comment]
Did not appear on "the bois" run so please let me know if it happens again.

**Comment by SimeonGavrilov** [comment]
np

**Comment by SimeonGavrilov** [comment]
![image](https://user-images.githubusercontent.com/52416849/79047012-31d68d00-7c25-11ea-9cf3-3711dd474cd1.png)

**Comment by SimeonGavrilov** [comment]
Fixed.
