### ISSUE TITLE
[Quest] Ancient Petrified Leaf - Hunters

### ISSUE THREAD

**Issue by Bucketbucket** [Hazor-Hellscream/Project-Hellscream-Info#778]
You can start the quest with the item, the characters are in felwood (I think) to hand the quest in, but you can't interact with him
![unknown](https://user-images.githubusercontent.com/63496484/79040616-97a12580-7be1-11ea-9e82-3f3e4d03be75.png)

**Comment by EyalMK** [comment]
This quest was deprecated in 4.0.3. Removed and fixed.
