### ISSUE TITLE
Shadowfang Keep dungeon.

### ISSUE THREAD

**Issue by Goretech** [Hazor-Hellscream/Project-Hellscream-Info#78]
Doors wont open.
Also completing dungeon in low lvl you get heroic archievement.

**Comment by ShaldarWoW** [comment]
Looks like the bosses, as well as some mobs in the instance are in Heroic difficulty, while the rest are scaled up to Normal mode.

**Comment by trilumx2** [comment]
the mobs are way over powered getting 1 shot death
