### ISSUE TITLE
quest The Wakening

### ISSUE THREAD

**Issue by ggrimlen** [Hazor-Hellscream/Project-Hellscream-Info#780]
https://www.wowhead.com/quest=24960/the-wakening

https://www.wowhead.com/npc=38895/lilian-voss
https://www.wowhead.com/npc=49230/marshal-redpath
https://www.wowhead.com/npc=49231/valdred-moray

dialogue does not work

**Comment by EyalMK** [comment]
Duplicate.
Tirisfal Glades is getting revamped. The Wakening is fixed but hasn't been pushed into the live realm yet.
