### ISSUE TITLE
combat bug ,  character health display

### ISSUE THREAD

**Issue by ggrimlen** [Hazor-Hellscream/Project-Hellscream-Info#792]
https://shadowlands.wowhead.com/npc=10081/dustwraith

**Comment by Goretech** [comment]
That npc gets you in combat for whole dungeon, you cant attack it.
IF you do it the "right" way around that npc attacks you after/during last boss.

**Comment by EyalMK** [comment]
Fixed. Please test :)

**Comment by Goretech** [comment]
Fixed, can be closed.
