### ISSUE TITLE
Quest - [Murder Was The Case That They Gave Me: 26209]

### ISSUE THREAD

**Issue by ShaldarWoW** [Hazor-Hellscream/Project-Hellscream-Info#8]
Quest - [Murder Was The Case That They Gave Me: 26209]

![unknown](https://user-images.githubusercontent.com/60824117/74090437-9f423200-4aab-11ea-8e91-db9c4e5e32eb.png)

Can't interact with Transient to get the 1st clue of the quest.

Priority: 
Low

WoW Head link:
(https://www.wowhead.com/quest=26209/murder-was-the-case-that-they-gave-me)

**Comment by Goretech** [comment]
Transient that gives you the 1st clue is in furlbrows pumpkin farm, not in jansen stead, same thing with thug that gives clue 4.
![WoWScrnShot_042020_012224](https://user-images.githubusercontent.com/60852022/79701432-c4ba9b80-82a5-11ea-86c0-2b5c3ff4bb6c.jpg)
![WoWScrnShot_042020_012249](https://user-images.githubusercontent.com/60852022/79701436-cab07c80-82a5-11ea-95f0-d328ea830d18.jpg)

**Comment by EyalMK** [comment]
Fixed, tested and closed.
