### ISSUE TITLE
NPC - [Lieutenant Valorcall: 2612]

### ISSUE THREAD

**Issue by szentigrad3** [Hazor-Hellscream/Project-Hellscream-Info#808]
npc does not walk up and down the path instead just sits near the alliance camp(refuge pointe) > https://www.wowhead.com/npc=2612/lieutenant-valorcall

**Comment by EyalMK** [comment]
Fixed. Please test.

**Comment by szentigrad3** [comment]
https://puu.sh/FyHf7/4a8220ac86.gif

**Comment by EyalMK** [comment]
Issue unrelated to pathing. Movement changes were made to the system and have been reverted.
Pathing works completely blizzlike for both NPCs. Wait for the live application.
Closed.
