### ISSUE TITLE
Quest - [Rejoining the Forest: 28228]

### ISSUE THREAD

**Issue by 601bukaj** [Hazor-Hellscream/Project-Hellscream-Info#89]
Information:
Can't bring Flourishing Protector back to the hill in the center of Irontree Woods because he is not spawned.

Priority:
Medium

WoWhead link:
https://www.wowhead.com/quest=28228/rejoining-the-forest

**Comment by 601bukaj** [comment]
Quest need to be turned in to pop up window as it does not have a turn in point.
![Capture](https://user-images.githubusercontent.com/60825730/75337689-bfd10100-588d-11ea-9be9-939e8a98652b.PNG)

**Comment by szentigrad3** [comment]
quest automatically is credited as complete without taking any action allowing the player to immediately hand it in.
