### ISSUE TITLE
Quest - [Feeding the Hungry and the Homeless: 26271]

### ISSUE THREAD

**Issue by ShaldarWoW** [Hazor-Hellscream/Project-Hellscream-Info#9]
Quest - [Feeding the Hungry and the Homeless: 26271]

![unknown](https://user-images.githubusercontent.com/60824117/74090542-c6e5ca00-4aac-11ea-877f-f93194546f93.png)

The homeless don't move to the deployed stew to eat.

Priority:
Low

WoW Head link:
(https://www.wowhead.com/quest=26271/feeding-the-hungry-and-the-hopeless)

**Comment by ShaldarWoW** [comment]
Still not working.

**Comment by Rorhn** [comment]
Still not working.

**Comment by EyalMK** [comment]
Fixed.
