### ISSUE TITLE
Guild Vendors missing heirlooms

### ISSUE THREAD

**Issue by yo931** [Hazor-Hellscream/Project-Hellscream-Info#911]
Polished Legplates of Valor 122251
Burnished Legplates of Might 122264 

Probably missing all legs except for Pristine Lightforge Legplates

**Comment by senbonsakura** [comment]
Yep missing these as well.

https://www.wowhead.com/item=122256/tattered-dreadmist-leggings
https://www.wowhead.com/item=122254/stained-shadowcraft-pants
https://www.wowhead.com/item=122253/mystical-kilt-of-elements

**Comment by Nyr97** [comment]
They're not missing. They're there, but you need to reach certain Guild reputation in order to see them.
