### ISSUE TITLE
Quest - [A Destiny of Flame and Sorrow: 28218]

### ISSUE THREAD

**Issue by 601bukaj** [Hazor-Hellscream/Project-Hellscream-Info#92]
Information:
Quest is auto-complete, all battles are spawned at once

Priority:
Low

WoWhead link:
https://www.wowhead.com/quest=28218/a-destiny-of-flame-and-sorrow

**Comment by szentigrad3** [comment]
quest is not offered after handing in > https://www.wowhead.com/quest=28217/wanted-the-demon-hunter

**Comment by szentigrad3** [comment]
all npcs are also spawned > https://puu.sh/Fz2Cg/0060bab22c.jpg
