### ISSUE TITLE
Quest - [Bodyguard for Hire: 5821]

### ISSUE THREAD

**Issue by szentigrad3** [Hazor-Hellscream/Project-Hellscream-Info#920]
quest automatically is credited as complete without taking any action allowing the player to immediately hand it in. > not sure if the quest npcs are in the right place > https://puu.sh/FAURX/d76e6a6c9a.jpg > https://www.wowhead.com/quest=5821/bodyguard-for-hire

**Comment by Bunnyblock2** [comment]
Worth noting that this quest was not attainable in Warlords of Draenor. It's up to server admins to decide if this quest should be included or not (it was removed accidentally due to Cross Realm Zoning in Mists of Pandaria, to this day in BFA it has still not returned)

**Comment by EyalMK** [comment]
Needs to be deprecated. It was not in WoD and therefore we will not have it in our WoD project.

**Comment by EyalMK** [comment]
Deprecated. Closed.
