### ISSUE TITLE
Quest - [The Fall of Tichondrius: 28257]

### ISSUE THREAD

**Issue by 601bukaj** [Hazor-Hellscream/Project-Hellscream-Info#93]
Information:
Quest is auto-complete, all battles are spawned at once

Priority:
Low

WoWhead link:
https://www.wowhead.com/quest=28257/the-fall-of-tichondrius

**Comment by szentigrad3** [comment]
all npcs are spawned > https://puu.sh/Fz2Cg/0060bab22c.jpg > not fixed as of 0.1.7
