### ISSUE TITLE
Quest - [Thunderdrome: The Ginormus!: 25067]

### ISSUE THREAD

**Issue by szentigrad3** [Hazor-Hellscream/Project-Hellscream-Info#966]
quest automatically is credited as complete without taking any action allowing the player to immediately hand it in > https://www.wowhead.com/quest=25067/thunderdrome-the-ginormus

**Comment by EyalMK** [comment]
Fixed. Please test after the update is applied.

**Comment by EyalMK** [comment]
Tested myself. Fixed.
