### ISSUE TITLE
Quest - [Thunderdrome: Zumonga!: 25094]

### ISSUE THREAD

**Issue by szentigrad3** [Hazor-Hellscream/Project-Hellscream-Info#967]
quest automatically is credited as complete without taking any action allowing the player to immediately hand it in > https://www.wowhead.com/quest=25094/thunderdrome-zumonga

**Comment by EyalMK** [comment]
Fixed. Please test after the update is applied.

**Comment by EyalMK** [comment]
Tested myself. Fixed.
