### ISSUE TITLE
Quest - [Thunderdrome: Sarinexx!: 25095]

### ISSUE THREAD

**Issue by szentigrad3** [Hazor-Hellscream/Project-Hellscream-Info#968]
quest automatically is credited as complete without taking any action allowing the player to immediately hand it in > https://www.wowhead.com/quest=25095/thunderdrome-sarinexx

**Comment by EyalMK** [comment]
Fixed. Please test after the update is applied.

**Comment by EyalMK** [comment]
Tested myself. Fixed.
