### ISSUE TITLE
Spell Issue - Resolve

### ISSUE THREAD

**Issue by Heimriel** [Hazor-Hellscream/Project-Hellscream-Info#972]
Hi Basically

Resolve for tanks doesn't provide the % required for the damage taken, this might be why tanks are squishy.

https://media.discordapp.net/attachments/671200627992297509/702912783301345350/unknown.png?width=1248&height=702
https://cdn.discordapp.com/attachments/671200627992297509/702913388266913792/unknown.png
https://cdn.discordapp.com/attachments/671200627992297509/702913659898298479/unknown.png

Please investigate, for all tank classes.

**Comment by EyalMK** [comment]
Duplicate. The second report you did had more info and Hazor fixed it. Thank you.
