### ISSUE TITLE
Razorfen Downs still loads OLD RFD

### ISSUE THREAD

**Issue by Heimriel** [Hazor-Hellscream/Project-Hellscream-Info#973]
Hello, I just completed RFD on Heimriel 60 Paladin

It doesn't reward a achievement at the end for the cold bringer and it still loads the old pre-cataclysm instance. 

Please have a look :)

**Comment by EyalMK** [comment]
Old Razorfen Downs is disabled and the new one is currently in development. It will not take too long to get the new dungeon with Glutton and Mordresh Fire-eye (and the others) up and running.

Closed. New Razorfen Downs is in-development.
