### ISSUE TITLE
Scarlet Monastary - Whitemane Overtuned

### ISSUE THREAD

**Issue by Heimriel** [Hazor-Hellscream/Project-Hellscream-Info#999]
Hello there

Just did a scarlet monastary cathedral run and whitemane is overtuned. 

Just to note this is Old scarlet monastary for some reason?

Scarlet Monastary was updated with a new dungeon and turned into 2 dungeons instead of 4.

Scarlet Halls and Scarlet Monastary. 

![image](https://user-images.githubusercontent.com/63412956/80222971-8a535480-863f-11ea-9a12-2961e27dcb35.png)

**Comment by EyalMK** [comment]
Scarlet Monastery and Scarlet Halls have been implemented in the core and are under development. They will be added very soon.

**Comment by EyalMK** [comment]
Closed due to the old dungeon not being relevant as of the next update.
